export const AGGREGATION_TREE_HEIGHT = 6;
export const TRANSFER_TREE_HEIGHT = 40;
export const GLOBAL_TRANSFER_TREE_HEIGHT = TRANSFER_TREE_HEIGHT + AGGREGATION_TREE_HEIGHT;
export const NUM_BATCH_INVOICES = 10;

export const DEFAULT_INDEXER_FETCH_LIMIT = 20;
export const DEFAULT_EVENT_BLOCK_SPAN = 5_000n;
export const DEFAULT_DECIDER_TIMEOUT_MS = 5 * 60 * 1000;
export const DEFAULT_DECIDER_POLL_INTERVAL_MS = 1_000;
